scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['192.168.29.21:3080']
        labels:
          service: 'my-service'
          group: 'production'
